server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: training-ms
    prefer-ip-address: true
    #    hostname: localhost

app:
  rest:
    client:
      courses-ms:
        url: http://courses-ms
